Improve rescreen sanity checks and comments

diff --git a/rescreen b/rescreen
--- a/rescreen
+++ b/rescreen
@@ -1,25 +1,37 @@
 #!/bin/sh
+set -u
 
-# put something like the following in your .bashrc
-# trap "if [ -f "$HOME/.rescreen_environment" ]; then source $HOME/.rescreen_environment; fi" SIGUSR1
+if [ ! $# = 1 ]; then
+    echo "Usage: rescreen sessionname"
+    exit 1
+fi
 
-OUTPUT="$HOME/.rescreen_environment"
+SESSION=$1
 
+# list of variables to reload in screen
 VARIABLES="SSH_CLIENT
 SSH_TTY
 SSH_AUTH_SOCK
 SSH_CONNECTION
 DISPLAY"
 
-SCREEN_NAME=$1
+OUTPUT="$HOME/.rescreen_environment"
+HANDLER='trap "if [ -f "$HOME/.rescreen_environment" ]; then source $HOME/.rescreen_environment; fi" SIGUSR1'
+
+# search bashrc for signal handler
+if ! grep -q "SIGUSR1" "$HOME/.bashrc"; then
+    echo "You must have the following in your .bashrc file for rescreen to work"
+    echo $HANDLER
+    exit 1 
+fi
 
 # format is pid.name
-PID_AND_NAME=$(screen -list | awk "/$SCREEN_NAME/ {print \$1}")
+PID_AND_NAME=$(screen -list | awk "/$SESSION/ {print \$1}")
 if [ -z "$PID_AND_NAME" ]; then
-    echo "There is no screen to be resumed matching $SCREEN_NAME."
+    echo "There is no screen to be resumed matching $SESSION."
     exit 1
 fi
-PID=${PID_AND_NAME%%.$SCREEN_NAME}
+PID=${PID_AND_NAME%%.$SESSION}
 
 if [ -f "$OUTPUT" ]; then
     rm $OUTPUT
@@ -28,16 +40,26 @@ fi
 for NAME in $VARIABLES; do
     VALUE=$(eval "echo \$$NAME")
     if [ -n "$VALUE" ]; then
-        screen -S $SCREEN_NAME -X setenv $NAME $VALUE
-        echo "export $NAME=$VALUE" >> $OUTPUT
+        # set variable in screen so will be inherited by future shells
+        screen -S $SESSION -X setenv $NAME $VALUE
+        # build file for existing shells to source
+        echo "export $NAME='$VALUE'" >> $OUTPUT
     fi
 done
 
 for CHILD_PID in $(ps --ppid $PID -o 'pid='); do
     CHILD_CMD=$(ps --pid $CHILD_PID -o 'cmd=')
     if [ "$CHILD_CMD" = '/bin/bash' ]; then
+        # trigger our signal handler in the shell
         kill -USR1 $CHILD_PID
     fi
+    if ! ps --pid $CHILD_PID > /dev/null; then
+        echo "Your shell seems to have died. Aborting!"
+        echo "Did you add the following to your .bashrc file?"
+        echo $HANDLER
+        exit 2
+    fi
+    
 done
 
-screen -r $SCREEN_NAME
+screen -r $SESSION
